name: Build WiFi Driver RTL88x2BU

on:
  workflow_dispatch: # Кнопка для ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Build Essentials
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libelf-dev bc flex bison libssl-dev

      - name: Download Kernel Headers
        run: |
          # По умолчанию берем ядро сервера. 
          # Для конкретной версии замени $(uname -r) на нужную, например 5.10.0-21-generic
          sudo apt-get install -y linux-headers-$(uname -r)
          echo "KDIR=/lib/modules/$(uname -r)/build" >> $GITHUB_ENV

      - name: Compile Module
        run: |
          # Переходим в папку подмодуля и запускаем сборку
          cd rtl88x2bu
          make -C ${{ env.KDIR }} M=$PWD modules

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 88x2bu-module
          path: rtl88x2bu/*.ko